spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  config:
    import: optional:file:.env[.properties]

  h2:
    console:
      enabled: true

  jwt:
    secret: ${JWT__SECRET_KEY}

springdoc:
  api-docs:
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

payment:
  secret-key: ${PAYMENT__SECRET_KEY}
  client-key: ${PAYMENT__CLIENT_KEY}
  customer-key: ${PAYMENT__CUSTOMER_KEY}