spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

  config:
    import: optional:file:.env[.properties]

  h2:
    console:
      enabled: true

  jwt:
    secret: ${JWT__SECRET_KEY}

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: aibe3-team4-bucket-1

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO__CLIENT_ID}
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope:
              - account_email
            authorization-grant-type: authorization_code
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

springdoc:
  api-docs:
    groups:
      enabled: true
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha

payment:
  secret-key: ${PAYMENT__SECRET_KEY}
